version: '3'

services:

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dockerpwd
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:
